# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
