# Generated by Django 2.0.7 on 2018-07-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0004_booklet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklet',
            options={'permissions': (('view_booklet', 'Can view booklet'),)},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'permissions': (('view_committee', 'Can view committee'),)},
        ),
        migrations.AlterModelOptions(
            name='delegate',
            options={'permissions': (('view_delegate', 'Can view delegate'),)},
        ),
        migrations.AlterModelOptions(
            name='delegation',
            options={'permissions': (('view_delegation', 'Can view delegation'),)},
        ),
    ]
