# Generated by Django 2.0.7 on 2018-07-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0005_auto_20180721_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='booklet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jurycore.Booklet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegate',
            name='booklet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jurycore.Booklet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegation',
            name='booklet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jurycore.Booklet'),
            preserve_default=False,
        ),
    ]
