# Generated by Django 2.0.7 on 2018-07-22 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0007_booklet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d2d1d73-0b87-4650-9f50-204ce6a05650'), editable=False),
        ),
        migrations.AddField(
            model_name='delegate',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d6f58c8-28ff-43ff-9e41-fc9fe33093d1'), editable=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b6422fd6-43b9-4350-8068-b1c5e620f9a6'), editable=False),
        ),
    ]
