# Generated by Django 2.0.7 on 2018-07-22 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jurycore', '0009_auto_20180722_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='booklet',
            name='author_name',
        ),
        migrations.AddField(
            model_name='booklet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('24b71cca-e68b-454c-bd81-c66345cf537b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f7da6bb9-3582-4e16-b635-51a1ad6b582a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0804e801-967e-4ce6-8d2f-4accb08836b7'), editable=False, unique=True),
        ),
    ]
