# Generated by Django 2.0.7 on 2018-07-22 18:35

import colorful.fields
from django.db import migrations, models
import jurycore.models


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0014_auto_20180722_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='photo',
            field=models.ImageField(upload_to=jurycore.models.Delegate.get_upload_path),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='colour',
            field=colorful.fields.RGBColorField(blank=True),
        ),
    ]
