# Generated by Django 2.0.7 on 2018-07-23 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0016_booklet_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
