# Generated by Django 2.1.7 on 2019-03-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurycore', '0017_auto_20180723_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='delegate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='delegation',
            options={},
        ),
    ]
